create table public.admin (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  email text null,
  password_hash text null,
  constraint admin_pkey primary key (id)
) TABLESPACE pg_default;


create table public.blogs (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  title text null,
  slug text null,
  excerpt text null,
  content text null,
  category text null,
  read_time text null,
  publish_date text null,
  thumbnail text null,
  constraint blogs_pkey primary key (id)
) TABLESPACE pg_default;

create table public.event_logs (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  event_type text null,
  page text null,
  metadata jsonb null,
  constraint event_logs_pkey primary key (id)
) TABLESPACE pg_default;

create table public.experience_points (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  experience_id text null,
  point text null,
  constraint experience_points_pkey primary key (id)
) TABLESPACE pg_default;

create table public.experiences (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  role text null,
  company text null,
  description text null,
  start_date text null,
  end_date text null,
  is_current text null
) TABLESPACE pg_default;


create table public.messages (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  email text null,
  subject text null,
  message text null,
  status text null,
  replied text null default 'false'::text,
  reply text null,
  constraint messages_pkey primary key (id)
) TABLESPACE pg_default;

create table public.project_technologies (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  project_id text null,
  technology text null,
  constraint project_technologies_pkey primary key (id)
) TABLESPACE pg_default;

create table public.projects (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  title text null,
  description text null,
  github_link text null,
  live_link text null,
  thumbnail text null,
  featured text null,
  constraint projects_pkey primary key (id)
) TABLESPACE pg_default;

create table public.skills (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  description text null,
  icon text null,
  percentage text null,
  order_index text null
) TABLESPACE pg_default;

create table public.social_links (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  platform text null,
  url text null,
  order_index text null,
  constraint social_links_pkey primary key (id)
) TABLESPACE pg_default;

create table public.testimonials (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  role text null,
  company text null,
  review text null,
  rating text null,
  avatar_initials text null,
  constraint testimonials_pkey primary key (id)
) TABLESPACE pg_default;

create table public.users (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  title text null,
  bio text null,
  location text null,
  email text null,
  linkedin text null,
  github text null,
  status text null,
  projects_count text null,
  tech_stack_count text null,
  template_id text null
) TABLESPACE pg_default;